//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachingJob.Templates.Pages {
    
    
    public partial class provide_work_permit_for_foreigner_laborers_working_in_vietnam {
        
        /// <summary>
        /// SocialLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TeachingJob.Templates.UserControl.SocialLinkArticle SocialLink;
        
        /// <summary>
        /// lbl_MainInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_MainInfo;
        
        /// <summary>
        /// ads control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TeachingJob.Templates.UserControl.IntershipAds ads;
    }
}
