#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TeachingJob")]
	public partial class TeachinVietnamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_TrainingLevel(tbl_TrainingLevel instance);
    partial void Updatetbl_TrainingLevel(tbl_TrainingLevel instance);
    partial void Deletetbl_TrainingLevel(tbl_TrainingLevel instance);
    partial void Inserttbl_TrainingCourse(tbl_TrainingCourse instance);
    partial void Updatetbl_TrainingCourse(tbl_TrainingCourse instance);
    partial void Deletetbl_TrainingCourse(tbl_TrainingCourse instance);
    partial void Inserttbl_Job_Sector(tbl_Job_Sector instance);
    partial void Updatetbl_Job_Sector(tbl_Job_Sector instance);
    partial void Deletetbl_Job_Sector(tbl_Job_Sector instance);
    partial void Inserttbl_Job_Location(tbl_Job_Location instance);
    partial void Updatetbl_Job_Location(tbl_Job_Location instance);
    partial void Deletetbl_Job_Location(tbl_Job_Location instance);
    partial void Inserttbl_intership_article(tbl_intership_article instance);
    partial void Updatetbl_intership_article(tbl_intership_article instance);
    partial void Deletetbl_intership_article(tbl_intership_article instance);
    partial void Inserttbl_Internship_UserSubmit(tbl_Internship_UserSubmit instance);
    partial void Updatetbl_Internship_UserSubmit(tbl_Internship_UserSubmit instance);
    partial void Deletetbl_Internship_UserSubmit(tbl_Internship_UserSubmit instance);
    partial void Inserttbl_service_article(tbl_service_article instance);
    partial void Updatetbl_service_article(tbl_service_article instance);
    partial void Deletetbl_service_article(tbl_service_article instance);
    partial void Inserttbl_feature_logo(tbl_feature_logo instance);
    partial void Updatetbl_feature_logo(tbl_feature_logo instance);
    partial void Deletetbl_feature_logo(tbl_feature_logo instance);
    partial void Inserttbl_Intership(tbl_Intership instance);
    partial void Updatetbl_Intership(tbl_Intership instance);
    partial void Deletetbl_Intership(tbl_Intership instance);
    #endregion
		
		public TeachinVietnamDataContext() : 
				base(global::BusinessLogic.Properties.Settings.Default.TeachingJobConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TeachinVietnamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TeachinVietnamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TeachinVietnamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TeachinVietnamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_TrainingLevel> tbl_TrainingLevels
		{
			get
			{
				return this.GetTable<tbl_TrainingLevel>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TrainingCourse> tbl_TrainingCourses
		{
			get
			{
				return this.GetTable<tbl_TrainingCourse>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Job_Sector> tbl_Job_Sectors
		{
			get
			{
				return this.GetTable<tbl_Job_Sector>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Job_Location> tbl_Job_Locations
		{
			get
			{
				return this.GetTable<tbl_Job_Location>();
			}
		}
		
		public System.Data.Linq.Table<tbl_intership_article> tbl_intership_articles
		{
			get
			{
				return this.GetTable<tbl_intership_article>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Internship_UserSubmit> tbl_Internship_UserSubmits
		{
			get
			{
				return this.GetTable<tbl_Internship_UserSubmit>();
			}
		}
		
		public System.Data.Linq.Table<tbl_service_article> tbl_service_articles
		{
			get
			{
				return this.GetTable<tbl_service_article>();
			}
		}
		
		public System.Data.Linq.Table<tbl_feature_logo> tbl_feature_logos
		{
			get
			{
				return this.GetTable<tbl_feature_logo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Intership> tbl_Interships
		{
			get
			{
				return this.GetTable<tbl_Intership>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_GetCoursesByLocation")]
		public ISingleResult<proc_GetCoursesByLocationResult> proc_GetCoursesByLocation([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string city)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), city);
			return ((ISingleResult<proc_GetCoursesByLocationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_GetCoursesByLocation")]
		public ISingleResult<proc_GetCoursesByLocationResult1> proc_GetCoursesByLocation1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string city)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), city);
			return ((ISingleResult<proc_GetCoursesByLocationResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_InsertTrainingCourse")]
		public int proc_InsertTrainingCourse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> tc_empId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tc_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tc_certificate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tc_category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tc_location, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tc_length, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tc_timetable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tc_cost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string tc_entryRequirement, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tc_contact, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string tc_courseContent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string tc_teacherBenefit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> tc_active)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tc_empId, tc_name, tc_certificate, tc_category, tc_location, tc_length, tc_timetable, tc_cost, tc_entryRequirement, tc_contact, tc_courseContent, tc_teacherBenefit, tc_active);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_deleteAIntershipArticle")]
		public int proc_deleteAIntershipArticle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_getAllIntership")]
		public ISingleResult<proc_getAllIntershipResult> proc_getAllIntership()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<proc_getAllIntershipResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_Internship_Guide_Insert")]
		public int proc_Internship_Guide_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string phone)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, firstname, lastname, email, country, phone);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_service_acticle_insert")]
		public int proc_service_acticle_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string maincontent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> displayOnMenu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> displayOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> active)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentId, title, maincontent, displayOnMenu, displayOrder, active);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_service_article_delete")]
		public int proc_service_article_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_service_article_getArticleById")]
		public ISingleResult<proc_service_article_getArticleByIdResult> proc_service_article_getArticleById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<proc_service_article_getArticleByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_service_article_updateArticleById")]
		public int proc_service_article_updateArticleById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string maincontent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> displayOnMenu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> displayOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> active)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, parentId, title, maincontent, displayOnMenu, displayOrder, active);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_service_article_hasParentNotRoot")]
		public ISingleResult<proc_service_article_hasParentNotRootResult> proc_service_article_hasParentNotRoot([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<proc_service_article_hasParentNotRootResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_service_article_GetSubArtiles")]
		public ISingleResult<proc_service_article_GetSubArtilesResult> proc_service_article_GetSubArtiles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<proc_service_article_GetSubArtilesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_feature_logo_insert")]
		public int proc_feature_logo_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> order)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, order);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_feature_logo_delete")]
		public int proc_feature_logo_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_feature_logo_GetById")]
		public ISingleResult<proc_feature_logo_GetByIdResult> proc_feature_logo_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<proc_feature_logo_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_feature_logo_update")]
		public int proc_feature_logo_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> active, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sortOrder)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, active, sortOrder);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_UpdateInternship")]
		public int proc_UpdateInternship([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string articleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string articleIntroduction, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string articleContent, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> active, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> enableFreeGuide, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> enableApplyOnline)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, articleName, articleIntroduction, articleContent, active, enableFreeGuide, enableApplyOnline);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_getIntershipById")]
		public ISingleResult<proc_getIntershipByIdResult> proc_getIntershipById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<proc_getIntershipByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_Internship_UserSubmit_Insert")]
		public int proc_Internship_UserSubmit_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string whenshouldwecall, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string cvPath)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, firstname, lastname, email, country, phone, whenshouldwecall, cvPath);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TrainingLevel")]
	public partial class tbl_TrainingLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tlId;
		
		private string _tlName_en;
		
		private string _tlName_vi;
		
		private EntitySet<tbl_TrainingCourse> _tbl_TrainingCourses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntlIdChanging(int value);
    partial void OntlIdChanged();
    partial void OntlName_enChanging(string value);
    partial void OntlName_enChanged();
    partial void OntlName_viChanging(string value);
    partial void OntlName_viChanged();
    #endregion
		
		public tbl_TrainingLevel()
		{
			this._tbl_TrainingCourses = new EntitySet<tbl_TrainingCourse>(new Action<tbl_TrainingCourse>(this.attach_tbl_TrainingCourses), new Action<tbl_TrainingCourse>(this.detach_tbl_TrainingCourses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tlId
		{
			get
			{
				return this._tlId;
			}
			set
			{
				if ((this._tlId != value))
				{
					this.OntlIdChanging(value);
					this.SendPropertyChanging();
					this._tlId = value;
					this.SendPropertyChanged("tlId");
					this.OntlIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlName_en", DbType="VarChar(100)")]
		public string tlName_en
		{
			get
			{
				return this._tlName_en;
			}
			set
			{
				if ((this._tlName_en != value))
				{
					this.OntlName_enChanging(value);
					this.SendPropertyChanging();
					this._tlName_en = value;
					this.SendPropertyChanged("tlName_en");
					this.OntlName_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlName_vi", DbType="NVarChar(100)")]
		public string tlName_vi
		{
			get
			{
				return this._tlName_vi;
			}
			set
			{
				if ((this._tlName_vi != value))
				{
					this.OntlName_viChanging(value);
					this.SendPropertyChanging();
					this._tlName_vi = value;
					this.SendPropertyChanged("tlName_vi");
					this.OntlName_viChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_TrainingLevel_tbl_TrainingCourse", Storage="_tbl_TrainingCourses", ThisKey="tlId", OtherKey="tc_certificate")]
		public EntitySet<tbl_TrainingCourse> tbl_TrainingCourses
		{
			get
			{
				return this._tbl_TrainingCourses;
			}
			set
			{
				this._tbl_TrainingCourses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_TrainingCourses(tbl_TrainingCourse entity)
		{
			this.SendPropertyChanging();
			entity.tbl_TrainingLevel = this;
		}
		
		private void detach_tbl_TrainingCourses(tbl_TrainingCourse entity)
		{
			this.SendPropertyChanging();
			entity.tbl_TrainingLevel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TrainingCourse")]
	public partial class tbl_TrainingCourse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _tc_id;
		
		private System.Nullable<System.Guid> _tc_empId;
		
		private string _tc_name;
		
		private System.Nullable<int> _tc_certificate;
		
		private System.Nullable<int> _tc_category;
		
		private System.Nullable<int> _tc_location;
		
		private string _tc_length;
		
		private string _tc_timetable;
		
		private string _tc_cost;
		
		private string _tc_entryRequirement;
		
		private string _tc_contact;
		
		private string _tc_courseContent;
		
		private string _tc_teacherBenefit;
		
		private System.Nullable<int> _tc_viewCount;
		
		private System.Nullable<System.DateTime> _tc_createdDate;
		
		private System.Nullable<bool> _tc_premium;
		
		private System.Nullable<bool> _tc_active;
		
		private EntityRef<tbl_TrainingLevel> _tbl_TrainingLevel;
		
		private EntityRef<tbl_Job_Sector> _tbl_Job_Sector;
		
		private EntityRef<tbl_Job_Location> _tbl_Job_Location;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontc_idChanging(short value);
    partial void Ontc_idChanged();
    partial void Ontc_empIdChanging(System.Nullable<System.Guid> value);
    partial void Ontc_empIdChanged();
    partial void Ontc_nameChanging(string value);
    partial void Ontc_nameChanged();
    partial void Ontc_certificateChanging(System.Nullable<int> value);
    partial void Ontc_certificateChanged();
    partial void Ontc_categoryChanging(System.Nullable<int> value);
    partial void Ontc_categoryChanged();
    partial void Ontc_locationChanging(System.Nullable<int> value);
    partial void Ontc_locationChanged();
    partial void Ontc_lengthChanging(string value);
    partial void Ontc_lengthChanged();
    partial void Ontc_timetableChanging(string value);
    partial void Ontc_timetableChanged();
    partial void Ontc_costChanging(string value);
    partial void Ontc_costChanged();
    partial void Ontc_entryRequirementChanging(string value);
    partial void Ontc_entryRequirementChanged();
    partial void Ontc_contactChanging(string value);
    partial void Ontc_contactChanged();
    partial void Ontc_courseContentChanging(string value);
    partial void Ontc_courseContentChanged();
    partial void Ontc_teacherBenefitChanging(string value);
    partial void Ontc_teacherBenefitChanged();
    partial void Ontc_viewCountChanging(System.Nullable<int> value);
    partial void Ontc_viewCountChanged();
    partial void Ontc_createdDateChanging(System.Nullable<System.DateTime> value);
    partial void Ontc_createdDateChanged();
    partial void Ontc_premiumChanging(System.Nullable<bool> value);
    partial void Ontc_premiumChanged();
    partial void Ontc_activeChanging(System.Nullable<bool> value);
    partial void Ontc_activeChanged();
    #endregion
		
		public tbl_TrainingCourse()
		{
			this._tbl_TrainingLevel = default(EntityRef<tbl_TrainingLevel>);
			this._tbl_Job_Sector = default(EntityRef<tbl_Job_Sector>);
			this._tbl_Job_Location = default(EntityRef<tbl_Job_Location>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short tc_id
		{
			get
			{
				return this._tc_id;
			}
			set
			{
				if ((this._tc_id != value))
				{
					this.Ontc_idChanging(value);
					this.SendPropertyChanging();
					this._tc_id = value;
					this.SendPropertyChanged("tc_id");
					this.Ontc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_empId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> tc_empId
		{
			get
			{
				return this._tc_empId;
			}
			set
			{
				if ((this._tc_empId != value))
				{
					this.Ontc_empIdChanging(value);
					this.SendPropertyChanging();
					this._tc_empId = value;
					this.SendPropertyChanged("tc_empId");
					this.Ontc_empIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_name", DbType="NVarChar(255)")]
		public string tc_name
		{
			get
			{
				return this._tc_name;
			}
			set
			{
				if ((this._tc_name != value))
				{
					this.Ontc_nameChanging(value);
					this.SendPropertyChanging();
					this._tc_name = value;
					this.SendPropertyChanged("tc_name");
					this.Ontc_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_certificate", DbType="Int")]
		public System.Nullable<int> tc_certificate
		{
			get
			{
				return this._tc_certificate;
			}
			set
			{
				if ((this._tc_certificate != value))
				{
					if (this._tbl_TrainingLevel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontc_certificateChanging(value);
					this.SendPropertyChanging();
					this._tc_certificate = value;
					this.SendPropertyChanged("tc_certificate");
					this.Ontc_certificateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_category", DbType="Int")]
		public System.Nullable<int> tc_category
		{
			get
			{
				return this._tc_category;
			}
			set
			{
				if ((this._tc_category != value))
				{
					if (this._tbl_Job_Sector.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontc_categoryChanging(value);
					this.SendPropertyChanging();
					this._tc_category = value;
					this.SendPropertyChanged("tc_category");
					this.Ontc_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_location", DbType="Int")]
		public System.Nullable<int> tc_location
		{
			get
			{
				return this._tc_location;
			}
			set
			{
				if ((this._tc_location != value))
				{
					if (this._tbl_Job_Location.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontc_locationChanging(value);
					this.SendPropertyChanging();
					this._tc_location = value;
					this.SendPropertyChanged("tc_location");
					this.Ontc_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_length", DbType="NVarChar(255)")]
		public string tc_length
		{
			get
			{
				return this._tc_length;
			}
			set
			{
				if ((this._tc_length != value))
				{
					this.Ontc_lengthChanging(value);
					this.SendPropertyChanging();
					this._tc_length = value;
					this.SendPropertyChanged("tc_length");
					this.Ontc_lengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_timetable", DbType="NVarChar(255)")]
		public string tc_timetable
		{
			get
			{
				return this._tc_timetable;
			}
			set
			{
				if ((this._tc_timetable != value))
				{
					this.Ontc_timetableChanging(value);
					this.SendPropertyChanging();
					this._tc_timetable = value;
					this.SendPropertyChanged("tc_timetable");
					this.Ontc_timetableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_cost", DbType="NVarChar(200)")]
		public string tc_cost
		{
			get
			{
				return this._tc_cost;
			}
			set
			{
				if ((this._tc_cost != value))
				{
					this.Ontc_costChanging(value);
					this.SendPropertyChanging();
					this._tc_cost = value;
					this.SendPropertyChanged("tc_cost");
					this.Ontc_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_entryRequirement", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_entryRequirement
		{
			get
			{
				return this._tc_entryRequirement;
			}
			set
			{
				if ((this._tc_entryRequirement != value))
				{
					this.Ontc_entryRequirementChanging(value);
					this.SendPropertyChanging();
					this._tc_entryRequirement = value;
					this.SendPropertyChanged("tc_entryRequirement");
					this.Ontc_entryRequirementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_contact", DbType="NVarChar(255)")]
		public string tc_contact
		{
			get
			{
				return this._tc_contact;
			}
			set
			{
				if ((this._tc_contact != value))
				{
					this.Ontc_contactChanging(value);
					this.SendPropertyChanging();
					this._tc_contact = value;
					this.SendPropertyChanged("tc_contact");
					this.Ontc_contactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_courseContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_courseContent
		{
			get
			{
				return this._tc_courseContent;
			}
			set
			{
				if ((this._tc_courseContent != value))
				{
					this.Ontc_courseContentChanging(value);
					this.SendPropertyChanging();
					this._tc_courseContent = value;
					this.SendPropertyChanged("tc_courseContent");
					this.Ontc_courseContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_teacherBenefit", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_teacherBenefit
		{
			get
			{
				return this._tc_teacherBenefit;
			}
			set
			{
				if ((this._tc_teacherBenefit != value))
				{
					this.Ontc_teacherBenefitChanging(value);
					this.SendPropertyChanging();
					this._tc_teacherBenefit = value;
					this.SendPropertyChanged("tc_teacherBenefit");
					this.Ontc_teacherBenefitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_viewCount", DbType="Int")]
		public System.Nullable<int> tc_viewCount
		{
			get
			{
				return this._tc_viewCount;
			}
			set
			{
				if ((this._tc_viewCount != value))
				{
					this.Ontc_viewCountChanging(value);
					this.SendPropertyChanging();
					this._tc_viewCount = value;
					this.SendPropertyChanged("tc_viewCount");
					this.Ontc_viewCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> tc_createdDate
		{
			get
			{
				return this._tc_createdDate;
			}
			set
			{
				if ((this._tc_createdDate != value))
				{
					this.Ontc_createdDateChanging(value);
					this.SendPropertyChanging();
					this._tc_createdDate = value;
					this.SendPropertyChanged("tc_createdDate");
					this.Ontc_createdDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_premium", DbType="Bit")]
		public System.Nullable<bool> tc_premium
		{
			get
			{
				return this._tc_premium;
			}
			set
			{
				if ((this._tc_premium != value))
				{
					this.Ontc_premiumChanging(value);
					this.SendPropertyChanging();
					this._tc_premium = value;
					this.SendPropertyChanged("tc_premium");
					this.Ontc_premiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_active", DbType="Bit")]
		public System.Nullable<bool> tc_active
		{
			get
			{
				return this._tc_active;
			}
			set
			{
				if ((this._tc_active != value))
				{
					this.Ontc_activeChanging(value);
					this.SendPropertyChanging();
					this._tc_active = value;
					this.SendPropertyChanged("tc_active");
					this.Ontc_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_TrainingLevel_tbl_TrainingCourse", Storage="_tbl_TrainingLevel", ThisKey="tc_certificate", OtherKey="tlId", IsForeignKey=true)]
		public tbl_TrainingLevel tbl_TrainingLevel
		{
			get
			{
				return this._tbl_TrainingLevel.Entity;
			}
			set
			{
				tbl_TrainingLevel previousValue = this._tbl_TrainingLevel.Entity;
				if (((previousValue != value) 
							|| (this._tbl_TrainingLevel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_TrainingLevel.Entity = null;
						previousValue.tbl_TrainingCourses.Remove(this);
					}
					this._tbl_TrainingLevel.Entity = value;
					if ((value != null))
					{
						value.tbl_TrainingCourses.Add(this);
						this._tc_certificate = value.tlId;
					}
					else
					{
						this._tc_certificate = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_TrainingLevel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Job_Sector_tbl_TrainingCourse", Storage="_tbl_Job_Sector", ThisKey="tc_category", OtherKey="seId", IsForeignKey=true)]
		public tbl_Job_Sector tbl_Job_Sector
		{
			get
			{
				return this._tbl_Job_Sector.Entity;
			}
			set
			{
				tbl_Job_Sector previousValue = this._tbl_Job_Sector.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Job_Sector.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Job_Sector.Entity = null;
						previousValue.tbl_TrainingCourses.Remove(this);
					}
					this._tbl_Job_Sector.Entity = value;
					if ((value != null))
					{
						value.tbl_TrainingCourses.Add(this);
						this._tc_category = value.seId;
					}
					else
					{
						this._tc_category = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Job_Sector");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Job_Location_tbl_TrainingCourse", Storage="_tbl_Job_Location", ThisKey="tc_location", OtherKey="lId", IsForeignKey=true)]
		public tbl_Job_Location tbl_Job_Location
		{
			get
			{
				return this._tbl_Job_Location.Entity;
			}
			set
			{
				tbl_Job_Location previousValue = this._tbl_Job_Location.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Job_Location.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Job_Location.Entity = null;
						previousValue.tbl_TrainingCourses.Remove(this);
					}
					this._tbl_Job_Location.Entity = value;
					if ((value != null))
					{
						value.tbl_TrainingCourses.Add(this);
						this._tc_location = value.lId;
					}
					else
					{
						this._tc_location = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Job_Location");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Job_Sector")]
	public partial class tbl_Job_Sector : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _seId;
		
		private string _seName_en;
		
		private string _seName_vi;
		
		private System.Nullable<int> _seParentId;
		
		private EntitySet<tbl_TrainingCourse> _tbl_TrainingCourses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnseIdChanging(int value);
    partial void OnseIdChanged();
    partial void OnseName_enChanging(string value);
    partial void OnseName_enChanged();
    partial void OnseName_viChanging(string value);
    partial void OnseName_viChanged();
    partial void OnseParentIdChanging(System.Nullable<int> value);
    partial void OnseParentIdChanged();
    #endregion
		
		public tbl_Job_Sector()
		{
			this._tbl_TrainingCourses = new EntitySet<tbl_TrainingCourse>(new Action<tbl_TrainingCourse>(this.attach_tbl_TrainingCourses), new Action<tbl_TrainingCourse>(this.detach_tbl_TrainingCourses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int seId
		{
			get
			{
				return this._seId;
			}
			set
			{
				if ((this._seId != value))
				{
					this.OnseIdChanging(value);
					this.SendPropertyChanging();
					this._seId = value;
					this.SendPropertyChanged("seId");
					this.OnseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seName_en", DbType="VarChar(100)")]
		public string seName_en
		{
			get
			{
				return this._seName_en;
			}
			set
			{
				if ((this._seName_en != value))
				{
					this.OnseName_enChanging(value);
					this.SendPropertyChanging();
					this._seName_en = value;
					this.SendPropertyChanged("seName_en");
					this.OnseName_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seName_vi", DbType="NVarChar(100)")]
		public string seName_vi
		{
			get
			{
				return this._seName_vi;
			}
			set
			{
				if ((this._seName_vi != value))
				{
					this.OnseName_viChanging(value);
					this.SendPropertyChanging();
					this._seName_vi = value;
					this.SendPropertyChanged("seName_vi");
					this.OnseName_viChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seParentId", DbType="Int")]
		public System.Nullable<int> seParentId
		{
			get
			{
				return this._seParentId;
			}
			set
			{
				if ((this._seParentId != value))
				{
					this.OnseParentIdChanging(value);
					this.SendPropertyChanging();
					this._seParentId = value;
					this.SendPropertyChanged("seParentId");
					this.OnseParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Job_Sector_tbl_TrainingCourse", Storage="_tbl_TrainingCourses", ThisKey="seId", OtherKey="tc_category")]
		public EntitySet<tbl_TrainingCourse> tbl_TrainingCourses
		{
			get
			{
				return this._tbl_TrainingCourses;
			}
			set
			{
				this._tbl_TrainingCourses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_TrainingCourses(tbl_TrainingCourse entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Job_Sector = this;
		}
		
		private void detach_tbl_TrainingCourses(tbl_TrainingCourse entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Job_Sector = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Job_Location")]
	public partial class tbl_Job_Location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lId;
		
		private string _lName_en;
		
		private string _lName_vi;
		
		private System.Nullable<int> _lParentId;
		
		private EntitySet<tbl_TrainingCourse> _tbl_TrainingCourses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlIdChanging(int value);
    partial void OnlIdChanged();
    partial void OnlName_enChanging(string value);
    partial void OnlName_enChanged();
    partial void OnlName_viChanging(string value);
    partial void OnlName_viChanged();
    partial void OnlParentIdChanging(System.Nullable<int> value);
    partial void OnlParentIdChanged();
    #endregion
		
		public tbl_Job_Location()
		{
			this._tbl_TrainingCourses = new EntitySet<tbl_TrainingCourse>(new Action<tbl_TrainingCourse>(this.attach_tbl_TrainingCourses), new Action<tbl_TrainingCourse>(this.detach_tbl_TrainingCourses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lId
		{
			get
			{
				return this._lId;
			}
			set
			{
				if ((this._lId != value))
				{
					this.OnlIdChanging(value);
					this.SendPropertyChanging();
					this._lId = value;
					this.SendPropertyChanged("lId");
					this.OnlIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lName_en", DbType="VarChar(100)")]
		public string lName_en
		{
			get
			{
				return this._lName_en;
			}
			set
			{
				if ((this._lName_en != value))
				{
					this.OnlName_enChanging(value);
					this.SendPropertyChanging();
					this._lName_en = value;
					this.SendPropertyChanged("lName_en");
					this.OnlName_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lName_vi", DbType="NVarChar(100)")]
		public string lName_vi
		{
			get
			{
				return this._lName_vi;
			}
			set
			{
				if ((this._lName_vi != value))
				{
					this.OnlName_viChanging(value);
					this.SendPropertyChanging();
					this._lName_vi = value;
					this.SendPropertyChanged("lName_vi");
					this.OnlName_viChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lParentId", DbType="Int")]
		public System.Nullable<int> lParentId
		{
			get
			{
				return this._lParentId;
			}
			set
			{
				if ((this._lParentId != value))
				{
					this.OnlParentIdChanging(value);
					this.SendPropertyChanging();
					this._lParentId = value;
					this.SendPropertyChanged("lParentId");
					this.OnlParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Job_Location_tbl_TrainingCourse", Storage="_tbl_TrainingCourses", ThisKey="lId", OtherKey="tc_location")]
		public EntitySet<tbl_TrainingCourse> tbl_TrainingCourses
		{
			get
			{
				return this._tbl_TrainingCourses;
			}
			set
			{
				this._tbl_TrainingCourses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_TrainingCourses(tbl_TrainingCourse entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Job_Location = this;
		}
		
		private void detach_tbl_TrainingCourses(tbl_TrainingCourse entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Job_Location = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_intership_article")]
	public partial class tbl_intership_article : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _body;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<int> _sort_order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void Onsort_orderChanging(System.Nullable<int> value);
    partial void Onsort_orderChanged();
    #endregion
		
		public tbl_intership_article()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="NVarChar(MAX)")]
		public string body
		{
			get
			{
				return this._body;
			}
			set
			{
				if ((this._body != value))
				{
					this.OnbodyChanging(value);
					this.SendPropertyChanging();
					this._body = value;
					this.SendPropertyChanged("body");
					this.OnbodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_order", DbType="Int")]
		public System.Nullable<int> sort_order
		{
			get
			{
				return this._sort_order;
			}
			set
			{
				if ((this._sort_order != value))
				{
					this.Onsort_orderChanging(value);
					this.SendPropertyChanging();
					this._sort_order = value;
					this.SendPropertyChanged("sort_order");
					this.Onsort_orderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Internship_UserSubmit")]
	public partial class tbl_Internship_UserSubmit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _email;
		
		private string _country;
		
		private string _phone;
		
		private string _whenshouldwecall;
		
		private System.Nullable<System.DateTime> _created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnwhenshouldwecallChanging(string value);
    partial void OnwhenshouldwecallChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    #endregion
		
		public tbl_Internship_UserSubmit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(255)")]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(255)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(255)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(255)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whenshouldwecall", DbType="NVarChar(255)")]
		public string whenshouldwecall
		{
			get
			{
				return this._whenshouldwecall;
			}
			set
			{
				if ((this._whenshouldwecall != value))
				{
					this.OnwhenshouldwecallChanging(value);
					this.SendPropertyChanging();
					this._whenshouldwecall = value;
					this.SendPropertyChanged("whenshouldwecall");
					this.OnwhenshouldwecallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_service_article")]
	public partial class tbl_service_article : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _parentId;
		
		private string _title;
		
		private string _maincontent;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<bool> _displayOnMenu;
		
		private System.Nullable<int> _displayOrder;
		
		private System.Nullable<bool> _active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnparentIdChanging(System.Nullable<int> value);
    partial void OnparentIdChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnmaincontentChanging(string value);
    partial void OnmaincontentChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OndisplayOnMenuChanging(System.Nullable<bool> value);
    partial void OndisplayOnMenuChanged();
    partial void OndisplayOrderChanging(System.Nullable<int> value);
    partial void OndisplayOrderChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
		
		public tbl_service_article()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int")]
		public System.Nullable<int> parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this.OnparentIdChanging(value);
					this.SendPropertyChanging();
					this._parentId = value;
					this.SendPropertyChanged("parentId");
					this.OnparentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maincontent", DbType="NVarChar(MAX)")]
		public string maincontent
		{
			get
			{
				return this._maincontent;
			}
			set
			{
				if ((this._maincontent != value))
				{
					this.OnmaincontentChanging(value);
					this.SendPropertyChanging();
					this._maincontent = value;
					this.SendPropertyChanged("maincontent");
					this.OnmaincontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayOnMenu", DbType="Bit")]
		public System.Nullable<bool> displayOnMenu
		{
			get
			{
				return this._displayOnMenu;
			}
			set
			{
				if ((this._displayOnMenu != value))
				{
					this.OndisplayOnMenuChanging(value);
					this.SendPropertyChanging();
					this._displayOnMenu = value;
					this.SendPropertyChanged("displayOnMenu");
					this.OndisplayOnMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayOrder", DbType="Int")]
		public System.Nullable<int> displayOrder
		{
			get
			{
				return this._displayOrder;
			}
			set
			{
				if ((this._displayOrder != value))
				{
					this.OndisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._displayOrder = value;
					this.SendPropertyChanged("displayOrder");
					this.OndisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_feature_logo")]
	public partial class tbl_feature_logo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _OrganizationName;
		
		private string _logo;
		
		private string _username;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<int> _SortOrder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnOrganizationNameChanging(string value);
    partial void OnOrganizationNameChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    #endregion
		
		public tbl_feature_logo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationName", DbType="NVarChar(255)")]
		public string OrganizationName
		{
			get
			{
				return this._OrganizationName;
			}
			set
			{
				if ((this._OrganizationName != value))
				{
					this.OnOrganizationNameChanging(value);
					this.SendPropertyChanging();
					this._OrganizationName = value;
					this.SendPropertyChanged("OrganizationName");
					this.OnOrganizationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(255)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Intership")]
	public partial class tbl_Intership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _articleName;
		
		private string _articleIntroduction;
		
		private string _articleContent;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<bool> _EnableFreeGuide;
		
		private System.Nullable<bool> _EnableApplyOnline;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnarticleNameChanging(string value);
    partial void OnarticleNameChanged();
    partial void OnarticleIntroductionChanging(string value);
    partial void OnarticleIntroductionChanged();
    partial void OnarticleContentChanging(string value);
    partial void OnarticleContentChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OnEnableFreeGuideChanging(System.Nullable<bool> value);
    partial void OnEnableFreeGuideChanged();
    partial void OnEnableApplyOnlineChanging(System.Nullable<bool> value);
    partial void OnEnableApplyOnlineChanged();
    #endregion
		
		public tbl_Intership()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleName", DbType="NVarChar(255)")]
		public string articleName
		{
			get
			{
				return this._articleName;
			}
			set
			{
				if ((this._articleName != value))
				{
					this.OnarticleNameChanging(value);
					this.SendPropertyChanging();
					this._articleName = value;
					this.SendPropertyChanged("articleName");
					this.OnarticleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleIntroduction", DbType="NVarChar(MAX)")]
		public string articleIntroduction
		{
			get
			{
				return this._articleIntroduction;
			}
			set
			{
				if ((this._articleIntroduction != value))
				{
					this.OnarticleIntroductionChanging(value);
					this.SendPropertyChanging();
					this._articleIntroduction = value;
					this.SendPropertyChanged("articleIntroduction");
					this.OnarticleIntroductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleContent", DbType="NVarChar(MAX)")]
		public string articleContent
		{
			get
			{
				return this._articleContent;
			}
			set
			{
				if ((this._articleContent != value))
				{
					this.OnarticleContentChanging(value);
					this.SendPropertyChanging();
					this._articleContent = value;
					this.SendPropertyChanged("articleContent");
					this.OnarticleContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableFreeGuide", DbType="Bit")]
		public System.Nullable<bool> EnableFreeGuide
		{
			get
			{
				return this._EnableFreeGuide;
			}
			set
			{
				if ((this._EnableFreeGuide != value))
				{
					this.OnEnableFreeGuideChanging(value);
					this.SendPropertyChanging();
					this._EnableFreeGuide = value;
					this.SendPropertyChanged("EnableFreeGuide");
					this.OnEnableFreeGuideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableApplyOnline", DbType="Bit")]
		public System.Nullable<bool> EnableApplyOnline
		{
			get
			{
				return this._EnableApplyOnline;
			}
			set
			{
				if ((this._EnableApplyOnline != value))
				{
					this.OnEnableApplyOnlineChanging(value);
					this.SendPropertyChanging();
					this._EnableApplyOnline = value;
					this.SendPropertyChanged("EnableApplyOnline");
					this.OnEnableApplyOnlineChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class proc_GetCoursesByLocationResult
	{
		
		private short _tc_empId;
		
		private string _tc_certificate;
		
		private string _tc_length;
		
		private string _tc_timetable;
		
		private string _tc_cost;
		
		private string _tc_entryRequirement;
		
		private string _tc_contact;
		
		private string _tc_courseContent;
		
		private string _tc_teacherBenefit;
		
		private System.Nullable<int> _tc_viewCount;
		
		private System.Nullable<bool> _tc_premium;
		
		public proc_GetCoursesByLocationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_empId", DbType="SmallInt NOT NULL")]
		public short tc_empId
		{
			get
			{
				return this._tc_empId;
			}
			set
			{
				if ((this._tc_empId != value))
				{
					this._tc_empId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_certificate", DbType="NVarChar(255)")]
		public string tc_certificate
		{
			get
			{
				return this._tc_certificate;
			}
			set
			{
				if ((this._tc_certificate != value))
				{
					this._tc_certificate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_length", DbType="VarChar(255)")]
		public string tc_length
		{
			get
			{
				return this._tc_length;
			}
			set
			{
				if ((this._tc_length != value))
				{
					this._tc_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_timetable", DbType="NVarChar(255)")]
		public string tc_timetable
		{
			get
			{
				return this._tc_timetable;
			}
			set
			{
				if ((this._tc_timetable != value))
				{
					this._tc_timetable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_cost", DbType="VarChar(200)")]
		public string tc_cost
		{
			get
			{
				return this._tc_cost;
			}
			set
			{
				if ((this._tc_cost != value))
				{
					this._tc_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_entryRequirement", DbType="NVarChar(255)")]
		public string tc_entryRequirement
		{
			get
			{
				return this._tc_entryRequirement;
			}
			set
			{
				if ((this._tc_entryRequirement != value))
				{
					this._tc_entryRequirement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_contact", DbType="NVarChar(255)")]
		public string tc_contact
		{
			get
			{
				return this._tc_contact;
			}
			set
			{
				if ((this._tc_contact != value))
				{
					this._tc_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_courseContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_courseContent
		{
			get
			{
				return this._tc_courseContent;
			}
			set
			{
				if ((this._tc_courseContent != value))
				{
					this._tc_courseContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_teacherBenefit", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_teacherBenefit
		{
			get
			{
				return this._tc_teacherBenefit;
			}
			set
			{
				if ((this._tc_teacherBenefit != value))
				{
					this._tc_teacherBenefit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_viewCount", DbType="Int")]
		public System.Nullable<int> tc_viewCount
		{
			get
			{
				return this._tc_viewCount;
			}
			set
			{
				if ((this._tc_viewCount != value))
				{
					this._tc_viewCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_premium", DbType="Bit")]
		public System.Nullable<bool> tc_premium
		{
			get
			{
				return this._tc_premium;
			}
			set
			{
				if ((this._tc_premium != value))
				{
					this._tc_premium = value;
				}
			}
		}
	}
	
	public partial class proc_GetCoursesByLocationResult1
	{
		
		private short _tc_empId;
		
		private string _tc_certificate;
		
		private string _tc_length;
		
		private string _tc_timetable;
		
		private string _tc_cost;
		
		private string _tc_entryRequirement;
		
		private string _tc_contact;
		
		private string _tc_courseContent;
		
		private string _tc_teacherBenefit;
		
		private System.Nullable<int> _tc_viewCount;
		
		private System.Nullable<bool> _tc_premium;
		
		private System.Nullable<bool> _tc_active;
		
		public proc_GetCoursesByLocationResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_empId", DbType="SmallInt NOT NULL")]
		public short tc_empId
		{
			get
			{
				return this._tc_empId;
			}
			set
			{
				if ((this._tc_empId != value))
				{
					this._tc_empId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_certificate", DbType="NVarChar(255)")]
		public string tc_certificate
		{
			get
			{
				return this._tc_certificate;
			}
			set
			{
				if ((this._tc_certificate != value))
				{
					this._tc_certificate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_length", DbType="VarChar(255)")]
		public string tc_length
		{
			get
			{
				return this._tc_length;
			}
			set
			{
				if ((this._tc_length != value))
				{
					this._tc_length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_timetable", DbType="NVarChar(255)")]
		public string tc_timetable
		{
			get
			{
				return this._tc_timetable;
			}
			set
			{
				if ((this._tc_timetable != value))
				{
					this._tc_timetable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_cost", DbType="VarChar(200)")]
		public string tc_cost
		{
			get
			{
				return this._tc_cost;
			}
			set
			{
				if ((this._tc_cost != value))
				{
					this._tc_cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_entryRequirement", DbType="NVarChar(255)")]
		public string tc_entryRequirement
		{
			get
			{
				return this._tc_entryRequirement;
			}
			set
			{
				if ((this._tc_entryRequirement != value))
				{
					this._tc_entryRequirement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_contact", DbType="NVarChar(255)")]
		public string tc_contact
		{
			get
			{
				return this._tc_contact;
			}
			set
			{
				if ((this._tc_contact != value))
				{
					this._tc_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_courseContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_courseContent
		{
			get
			{
				return this._tc_courseContent;
			}
			set
			{
				if ((this._tc_courseContent != value))
				{
					this._tc_courseContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_teacherBenefit", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tc_teacherBenefit
		{
			get
			{
				return this._tc_teacherBenefit;
			}
			set
			{
				if ((this._tc_teacherBenefit != value))
				{
					this._tc_teacherBenefit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_viewCount", DbType="Int")]
		public System.Nullable<int> tc_viewCount
		{
			get
			{
				return this._tc_viewCount;
			}
			set
			{
				if ((this._tc_viewCount != value))
				{
					this._tc_viewCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_premium", DbType="Bit")]
		public System.Nullable<bool> tc_premium
		{
			get
			{
				return this._tc_premium;
			}
			set
			{
				if ((this._tc_premium != value))
				{
					this._tc_premium = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_active", DbType="Bit")]
		public System.Nullable<bool> tc_active
		{
			get
			{
				return this._tc_active;
			}
			set
			{
				if ((this._tc_active != value))
				{
					this._tc_active = value;
				}
			}
		}
	}
	
	public partial class proc_getAllIntershipResult
	{
		
		private int _id;
		
		private string _articleName;
		
		private string _articleIntroduction;
		
		private string _articleContent;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<bool> _active;
		
		public proc_getAllIntershipResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleName", DbType="NVarChar(255)")]
		public string articleName
		{
			get
			{
				return this._articleName;
			}
			set
			{
				if ((this._articleName != value))
				{
					this._articleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleIntroduction", DbType="NVarChar(MAX)")]
		public string articleIntroduction
		{
			get
			{
				return this._articleIntroduction;
			}
			set
			{
				if ((this._articleIntroduction != value))
				{
					this._articleIntroduction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleContent", DbType="NVarChar(MAX)")]
		public string articleContent
		{
			get
			{
				return this._articleContent;
			}
			set
			{
				if ((this._articleContent != value))
				{
					this._articleContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this._createdDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
	}
	
	public partial class proc_service_article_getArticleByIdResult
	{
		
		private int _id;
		
		private System.Nullable<int> _parentId;
		
		private string _title;
		
		private string _maincontent;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<bool> _displayOnMenu;
		
		private System.Nullable<int> _displayOrder;
		
		private System.Nullable<bool> _active;
		
		public proc_service_article_getArticleByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int")]
		public System.Nullable<int> parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this._parentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maincontent", DbType="NVarChar(MAX)")]
		public string maincontent
		{
			get
			{
				return this._maincontent;
			}
			set
			{
				if ((this._maincontent != value))
				{
					this._maincontent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this._createdDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayOnMenu", DbType="Bit")]
		public System.Nullable<bool> displayOnMenu
		{
			get
			{
				return this._displayOnMenu;
			}
			set
			{
				if ((this._displayOnMenu != value))
				{
					this._displayOnMenu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayOrder", DbType="Int")]
		public System.Nullable<int> displayOrder
		{
			get
			{
				return this._displayOrder;
			}
			set
			{
				if ((this._displayOrder != value))
				{
					this._displayOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
	}
	
	public partial class proc_service_article_hasParentNotRootResult
	{
		
		private System.Nullable<int> _parentId;
		
		public proc_service_article_hasParentNotRootResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int")]
		public System.Nullable<int> parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this._parentId = value;
				}
			}
		}
	}
	
	public partial class proc_service_article_GetSubArtilesResult
	{
		
		private int _id;
		
		private System.Nullable<int> _parentId;
		
		private string _title;
		
		private string _maincontent;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<bool> _displayOnMenu;
		
		private System.Nullable<int> _displayOrder;
		
		private System.Nullable<bool> _active;
		
		public proc_service_article_GetSubArtilesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parentId", DbType="Int")]
		public System.Nullable<int> parentId
		{
			get
			{
				return this._parentId;
			}
			set
			{
				if ((this._parentId != value))
				{
					this._parentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(255)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maincontent", DbType="NVarChar(MAX)")]
		public string maincontent
		{
			get
			{
				return this._maincontent;
			}
			set
			{
				if ((this._maincontent != value))
				{
					this._maincontent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this._createdDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayOnMenu", DbType="Bit")]
		public System.Nullable<bool> displayOnMenu
		{
			get
			{
				return this._displayOnMenu;
			}
			set
			{
				if ((this._displayOnMenu != value))
				{
					this._displayOnMenu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_displayOrder", DbType="Int")]
		public System.Nullable<int> displayOrder
		{
			get
			{
				return this._displayOrder;
			}
			set
			{
				if ((this._displayOrder != value))
				{
					this._displayOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
	}
	
	public partial class proc_feature_logo_GetByIdResult
	{
		
		private int _id;
		
		private string _OrganizationName;
		
		private string _logo;
		
		private string _username;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<int> _SortOrder;
		
		public proc_feature_logo_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationName", DbType="NVarChar(255)")]
		public string OrganizationName
		{
			get
			{
				return this._OrganizationName;
			}
			set
			{
				if ((this._OrganizationName != value))
				{
					this._OrganizationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(255)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this._logo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this._SortOrder = value;
				}
			}
		}
	}
	
	public partial class proc_getIntershipByIdResult
	{
		
		private int _id;
		
		private string _articleName;
		
		private string _articleIntroduction;
		
		private string _articleContent;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.Guid> _author;
		
		private System.Nullable<bool> _EnableFreeGuide;
		
		private System.Nullable<bool> _EnableApplyOnline;
		
		public proc_getIntershipByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleName", DbType="NVarChar(255)")]
		public string articleName
		{
			get
			{
				return this._articleName;
			}
			set
			{
				if ((this._articleName != value))
				{
					this._articleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleIntroduction", DbType="NVarChar(MAX)")]
		public string articleIntroduction
		{
			get
			{
				return this._articleIntroduction;
			}
			set
			{
				if ((this._articleIntroduction != value))
				{
					this._articleIntroduction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_articleContent", DbType="NVarChar(MAX)")]
		public string articleContent
		{
			get
			{
				return this._articleContent;
			}
			set
			{
				if ((this._articleContent != value))
				{
					this._articleContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this._createdDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this._author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableFreeGuide", DbType="Bit")]
		public System.Nullable<bool> EnableFreeGuide
		{
			get
			{
				return this._EnableFreeGuide;
			}
			set
			{
				if ((this._EnableFreeGuide != value))
				{
					this._EnableFreeGuide = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableApplyOnline", DbType="Bit")]
		public System.Nullable<bool> EnableApplyOnline
		{
			get
			{
				return this._EnableApplyOnline;
			}
			set
			{
				if ((this._EnableApplyOnline != value))
				{
					this._EnableApplyOnline = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
